
'use client';
import Link from "next/link";
import { ReactTyped } from "react-typed";
import { motion } from 'framer-motion'

function Hero() {
    return (
        <motion.div
            initial={{ opacity: 0, scale: 0.8, z: -200 }}
            animate={{ opacity: 1, scale: 1, z: 0 }}
            exit={{ opacity: 0, scale: 0.8, z: -200 }}
            transition={{ duration: 0.7, type: "spring", stiffness: 80 }}
            id="hero"
            className="max-w-[800px] mt-[-96px] w-full h-screen mx-auto text-center flex flex-col justify-center px-4 sm:px-0">
            <h1 className="md:text-3xl sm:text-6xl text-3xl font-bold md:py-6">Know Your Strengths, Unlock New Opportunities</h1>
            <p className="md:text-base text-base font-medium py-2 text-secondary">
                Submit your structured data and receive intelligent, instant feedback generated by advanced AI models.
            </p>
            <p className="text-xs mt-1 text-secondary">
                From form to feedback, instantly harness AI to turn your data into
                <ReactTyped
                    className="md:text-xs sm:text-xs text-xs font-semibold inline-block ml-1"
                    strings={['decisions', 'insights', 'actions']}
                    typeSpeed={120}
                    backSpeed={140}
                    loop
                />.
            </p>
            <Link
                href={"/take-test"}
            > <button className="w-[200px] rounded-md font-medium my-6 mx-auto py-3">
                    Start Skill Check
                </button>
            </Link>
        </motion.div>
    );
}

export default Hero;