
'use client';
import Link from "next/link";
import { ReactTyped } from "react-typed";

function Hero() {
    return (<div className="w-full h-screen">
        <div className="max-w-[800px] mt-[-96px] w-full h-screen mx-auto text-center flex flex-col justify-center">
            <h1 className="md:text-3xl sm:text-6xl text-3xl font-bold md:py-6">Know Your Strengths, Unlock New Opportunities</h1>
            <p className="md:text-base text-base font-medium py-2 text-secondary">
                Submit your structured data and receive intelligent, instant feedback generated by advanced AI models.
            </p>
            <p className="text-xs mt-1 text-secondary">
                From form to feedback, instantly harness AI to turn your data into
                <ReactTyped
                    className="md:text-xs sm:text-xs text-xs font-semibold inline-block ml-1"
                    strings={['decisions', 'insights', 'actions']}
                    typeSpeed={120}
                    backSpeed={140}
                    loop
                />.
            </p>
            <Link
                href={"/take-test"}
            > <button className="w-[200px] rounded-md font-medium my-6 mx-auto py-3">
                    Start Skill Check
                </button>
            </Link>
        </div>
    </div>);
}

export default Hero;